> @Author.Name{Izzar Suly Nashrudin}

# **Python Collections (Arrays)**

There are four collection data types in the Python programming language:
* **List** is a collection which is ordered and changeable. Allows duplicate members.
* **Tuple** is a collection which is ordered and unchangeable. Allows duplicate members.
* **Set** is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
* **Dictionary** is a collection which is ordered** and changeable. No duplicate members.

Set items are unchangeable, but you can remove and/or add items whenever you like.As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.

## **Strings**
Strings in python are surrounded by either single quotation marks, or double quotation marks.
`'hello'` is the same as `"hello"`
You can display a string literal with the `print() `function:

In [ ]:
print("Hello")
print('Hello')

Hello
Hello

### **Assign String to a Variable**
Assigning a string to a variable is done with the variable name followed by an equal sign and the string:

In [ ]:
a = "Hello"
print(a)

Hello

### **Multiline Strings**
You can assign a multiline string to a variable by using three quotes:

In [ ]:
a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)
print("/n")
# Or three single quotes:
b = '''Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.'''
print(b)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.
/n
Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.

### **Strings are Arrays**
Like many other popular programming languages, strings in Python are arrays of bytes representing
unicode characters.
However, Python does not have a character data type, a single character is simply a string with a length of
1.
Square brackets can be used to access elements of the string.

In [ ]:
# Get the character at position 1 (remember that the first character has the posi
a = "Hello, World!"
print(a[1])

e

### **Looping Through a String**
Since strings are arrays, we can loop through the characters in a string, with a for loop.

In [ ]:
# Loop through the letters in the word "banana":
for x in "banana":
 print(x)

b
a
n
a
n
a

### **String Length**
To get the length of a string, use the `len()` function.

In [ ]:
# The len() function returns the length of a string:
a = "Hello, World!"
print(len(a))

13

### **Check String**
To check if a certain phrase or character is present in a string, we can use the keyword `in`

In [ ]:
# Check if "free" is present in the following text:
txt = "The best things in life are free!"
print("free" in txt)
# Use it in an if statement:
# Print only if "free" is present:
txt = "The best things in life are free!"
if "free" in txt:
 print("Yes, 'free' is present.")

True
Yes, 'free' is present.

### **Check if NOT**
To check if a certain phrase or character is NOT present in a string, we can use the keyword `not in`

In [ ]:
# Check if "expensive" is NOT present in the following text:
txt = "The best things in life are free!"
print("expensive" not in txt)
# Use it in an if statement:
# print only if "expensive" is NOT present:
txt = "The best things in life are free!"
if "expensive" not in txt:
 print("No, 'expensive' is NOT present.")

True
No, 'expensive' is NOT present.

### **Slicing**
You can return a range of characters by using the slice syntax.
Specify the start index and the end index, separated by a colon, to return a part of the string.

In [ ]:
# Get the characters from position 2 to position 5 (not included):
b = "Hello, World!"
print(b[2:5])
# Note: The first character has index 0.

llo

####**Slice From the Start**
By leaving out the start index, the range will start at the first character:

In [ ]:
# Get the characters from the start to position 5 (not included):
b = "Hello, World!"
print(b[:5])

Hello

####**Slice To the End**
By leaving out the end index, the range will go to the end:

In [ ]:
# Get the characters from position 2, and all the way to the end:
b = "Hello, World!"
print(b[2:])

llo, World!

### **Negative Indexing**
Use negative indexes to start the slice from the end of the string: Example

In [ ]:
# Get the characters:
# From: "o" in "World!" (position -5)
# To, but not included: "d" in "World!" (position -2):
b = "Hello, World!"
print(b[-5:-2])

orl

## **Modify Strings**
Python has a set of built-in methods that you can use on strings.

### **Upper Case**
The `upper()` method returns the string in upper case:

In [ ]:
a = "Hello, World!"
print(a.upper())

HELLO, WORLD!

### **Lower Case**
The `lower()` method returns the string in lower case:

In [ ]:
a = "Hello, World!"
print(a.lower())

hello, world!

### **Remove Whitespace**
Whitespace is the space before and/or after the actual text, and very often you want to remove this space.
The s`trip()` method removes any whitespace from the beginning or the end:

In [ ]:
a = " Hello, World!. "
print(a.strip()) # returns "Hello, World!"

Hello, World!.

### **Replace String**
The `replace()` method replaces a string with another string:

In [ ]:
a = "Hello, World!"
print(a.replace("H", "J"))

Jello, World!

### **Split String**
The `split()` method returns a list where the text between the specified separator becomes the list
items.
The `split(`) method splits the string into substrings if it finds instances of the separator:

In [ ]:
a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']

['Hello', ' World!']

## **String Concatenation**
To concatenate, or combine, two strings you can use the + operator

In [ ]:
# Merge variable a with variable b into variable c:
a = "Hello"
b = "World"
c = a + b
print(c)
# Add a space between them, add a " ":
a = "Hello"
b = "World"
c = a + " " + b
print(c)

HelloWorld
Hello World

## List
Lists are used to store multiple items in a single variable.
Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set,
and Dictionary, all with different qualities and usage.
Lists are created using square brackets `( [ ] )` or `list()` method:

In [ ]:
thislist = ["apple", "banana", "cherry"]
print(thislist)

['apple', 'banana', 'cherry']

### **List Items**
List items are ordered, changeable, and allow duplicate values.
List items are indexed, the first item has index `[0]` , the second item has index `[1]` etc.

### **Ordered**
When we say that lists are ordered, it means that the items have a defined order, and that order will not
change.
If you add new items to a list, the new items will be placed at the end of the list

### **Changeable (Mutable)**
The list is changeable, meaning that we can change, add, and remove items in a list after it has been
created.

### **Allow Duplicates**
Since lists are indexed, lists can have items with the same value:

In [ ]:
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

['apple', 'banana', 'cherry', 'apple', 'cherry']

### **List Length**
To determine how many items a list has, use the `len()` function:

In [ ]:
thislist = ["apple", "banana", "cherry"]
print(len(thislist))

3

### **List Items - Data Types**
List items can be of any data type:
A list can contain different data types:



```
# String, int and boolean data types:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
```


```
# A list with strings, integers and boolean values:
list1 = ["abc", 34, True, 40, "male"]
```

### **The `list()` Constructor**
It is also possible to use the `list() `constructor when creating a new list.

In [ ]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

['apple', 'banana', 'cherry']

### **Access List Items**
List items are indexed and you can access them by referring to the index number:

In [ ]:
# Print the second item of the list:
thislist = ["apple", "banana", "cherry"]
print(thislist[1])
# Note: The first item has index 0.

banana

### **Negative Indexing**
Negative indexing means start from the end. `-1` refers to the last item, `-2` refers to the second last item etc.

In [ ]:
# Print the last item of the list:
thislist = ["apple", "banana", "cherry"]
print(thislist[-1])

cherry

### **Range of Indexes**
You can specify a range of indexes by specifying where to start and where to end the range.
When specifying a range, the return value will be a new list with the specified items.

In [ ]:
# Return the third, fourth, and fifth item:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

['cherry', 'orange', 'kiwi']

**Note**: The search will start at index 2 (included) and end at index 5 (not included).
Remember that the first item has index 0.
By leaving out the start value, the range will start at the first item:

In [ ]:
# This example returns the items from the beginning to, but NOT including, "kiwi"
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[:4])

['apple', 'banana', 'cherry', 'orange']

By leaving out the end value, the range will go on to the end of the list

In [ ]:
# This example returns the items from "cherry" to the end:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:])

['cherry', 'orange', 'kiwi', 'melon', 'mango']

### **Range of Negative Indexes**
Specify negative indexes if you want to start the search from the end of the list:

In [ ]:
# This example returns the items from "orange" (-4) to, but NOT including "mango"
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

['orange', 'kiwi', 'melon']

### **Check if Item Exists**
To determine if a specified item is present in a list use the `in` keyword:

In [ ]:
# Check if "apple" is present in the list:
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
 print("Yes, 'apple' is in the fruits list")

Yes, 'apple' is in the fruits list

### **Change Item Value**
To change the value of a specific item, refer to the index number:

In [ ]:
# Change the second item:
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

['apple', 'blackcurrant', 'cherry']

### **Append Items**
To add an item to the end of the list, use the `append()` method:

In [ ]:
# Using the append() method to append an item:
thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

['apple', 'banana', 'cherry', 'orange']

### **Insert Items**
To insert a list item at a specified index, use the `insert()` method.
The `insert()` Inline code method inserts an item at the specified index:

In [ ]:
# Insert an item as the second position:
thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

['apple', 'orange', 'banana', 'cherry']

Extend List
To append elements from another list to the current list, use the `extend()` method.

In [ ]:
# Add the elements of tropical to thislist:
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)
# Note: The extend() method does not have to append lists,
# you can add any iterable object (tuples, sets, bdictionaries etc.).

['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']

### **Remove Specified Item**
The `remove()` method removes the specified item.

In [ ]:
# Remove "banana":
thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

['apple', 'cherry']

If there are more than one item with the specified value, the `remove()` method removes the first
occurance:

In [ ]:
# Remove the first occurance of "banana":
thislist = ["apple", "banana", "cherry", "banana", "kiwi"]
thislist.remove("banana")
print(thislist)

['apple', 'cherry', 'banana', 'kiwi']

### **Remove Specified Index**
The `pop()` method removes the specified index.

In [ ]:
# Remove the second item:
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)

['apple', 'cherry']

If you do not specify the index, the `pop()` method removes the last item.

In [ ]:
# Remove the last item:
thislist = ["apple", "banana", "cherry"]
thislist.pop()
print(thislist)

['apple', 'banana']

The `del` keyword also removes the specified index or delete the list completely:

In [ ]:
# Remove the first item:
thislist = ["apple", "banana", "cherry"]
del thislist[0]
print(thislist)
del thislist

['banana', 'cherry']

### **Clear the List**
The `clear()` method empties the list.
The list still remains, but it has no content.

In [ ]:
# Clear the list content:
thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

[]

### **Loop Through a List using `for`**
You can loop through the list items by using a for loop:

In [ ]:
# Print all items in the list, one by one:
thislist = ["apple", "banana", "cherry"]
for x in thislist:
 print(x)

apple
banana
cherry

### **Loop Through the Index Numbers**
You can also loop through the list items by referring to their index number.
Use the `range()` and `len()` functions to create a suitable iterable.

In [ ]:
# Print all items by referring to their index number:
thislist = ["apple", "banana", "cherry"]
for i in range(len(thislist)):
 print(thislist[i])

apple
banana
cherry

**Write loop through list using while!**

In [ ]:
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
    print(thislist[i])
    i += 1

apple
banana
cherry

### **Looping Using List Comprehension**
List Comprehension offers the shortest syntax for looping through lists:
A short hand for loop that will print all items in a list:

In [ ]:
thislist = ["apple", "banana", "cherry"]
[print(x) for x in thislist]

apple
banana
cherry

[None, None, None]

## **List Comprehension**
List comprehension offers a shorter syntax when you want to create a new list based on the values of an
existing list.
Example:
Based on a list of fruits, you want a new list, containing only the fruits with the letter "a" in the name.
Without list comprehension you will have to write a `for` statement with a conditional test inside:

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []
for x in fruits:
  if "a" in x:
    newlist.append(x)
print(newlist)

['apple', 'banana', 'mango']

With list comprehension you can do all that with only one line of code:

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = [x for x in fruits if "a" in x]
print(newlist)

['apple', 'banana', 'mango']

### **The Syntax**
> `newlist = [expression for item in iterable if condition == True]`

The return value is a new list, leaving the old list unchanged. The condition is like a filter that only accepts
the items that valuate to `True` .

In [ ]:
# Only accept items that are not "apple":
newlist = [x for x in fruits if x != "apple"]
print(newlist)

['banana', 'cherry', 'kiwi', 'mango']

The condition `if x != "apple"` will return `True` for all elements other than "apple", making the new
list contain all fruits except "apple".
The condition is optional and can be omitted:

In [ ]:
# Without if statement:
newlist = [x for x in fruits]
print(newlist)

['apple', 'banana', 'cherry', 'kiwi', 'mango']

More detail, visit w3schools.com list comprehension

### **Sort List**
List objects have a `sort()` method that will sort the list alphanumerically, ascending, by default:

In [ ]:
# Sort the list alphabetically:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)
# Sort the list numerically:
thislist = [100, 50, 65, 82, 23]
thislist.sort()
print(thislist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']
[23, 50, 65, 82, 100]

### **Sort Descending**
To sort descending, use the keyword argument `reverse = True` :

In [ ]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse = True)
print(thislist)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']

### **Reverse Order**
The `reverse()` method reverses the current sorting order of the elements.

In [ ]:
# Reverse the order of the list items:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.reverse()
print(thislist)

['cherry', 'Kiwi', 'Orange', 'banana']

### **Copy a List**
You cannot copy a list simply by typing `list2 = list1` , because: `list2` will only be a reference to
`list1` , and changes made in `list1` will automatically also be made in `list2` .
There are ways to make a copy, one way is to use the built-in List method `copy()` .

In [ ]:
# Make a copy of a list with the copy() method:
thislist = ["apple", "banana", "cherry"]
mylist = thislist.copy()
print(mylist)

['apple', 'banana', 'cherry']

Another way to make a copy is to use the built-in method `list(`) .

In [ ]:
# Make a copy of a list with the list() method:
thislist = ["apple", "banana", "cherry"]
mylist = list(thislist)
print(mylist)

['apple', 'banana', 'cherry']

### **Join Two Lists**
There are several ways to join, or concatenate, two or more lists in Python. One of the easiest ways are by using the `+` operator.

In [ ]:
list1 = ["a", "b", "c"]
list2 = [1, 2, 3]
list3 = list1 + list2
print(list3)

['a', 'b', 'c', 1, 2, 3]

Another way to join two lists is by appending all the items from `list2` into `list1` , one by one:

In [ ]:
# Append list2 into list1:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]
for x in list2:
 list1.append(x)
print(list1)

['a', 'b', 'c', 1, 2, 3]

Or you can use the `extend()` method, where the purpose is to add elements from one list to another list:

In [ ]:
# Use the extend() method to add list2 at the end of list1:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]
list1.extend(list2)
print(list1)

['a', 'b', 'c', 1, 2, 3]

## **Tuple**
A tuple is a collection which is ordered and unchangeable.
Tuples are written with round brackets.
The characteristics are the same as lists, the only difference is that tuple elements cannot be changed.

In [ ]:
# Create a tuple
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


**Unchangeable**
Tuples are unchangeable, meaning that we cannot change, add or remove items after the tuple has been
created.

### **Create Tuple With One Item**
To create a tuple with only one item, you have to add a comma after the item, otherwise Python will not
recognize it as a tuple

In [ ]:
# One item tuple, remember the comma:
thistuple = ("apple",)
print(type(thistuple))
# NOT a tuple
thistuple = ("apple")
print(type(thistuple))

<class 'tuple'>
<class 'str'>

### **The `tuple()` Constructor**
It is also possible to use the `tuple()` constructor to make a tuple.

In [ ]:
# Print the second item of the list:
thislist = ["apple", "banana", "cherry"]
print(thislist[1])
# Note: The first item has index 0.

banana

### **Change Tuple Values**
Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is
called.
But there is a workaround.
> You can convert the tuple into a list, change the list, and convert the list back
into a tuple.

In [ ]:
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)
print(x)

('apple', 'kiwi', 'cherry')

### **Add Items**
Since tuples are immutable, they do not have a built-in append() method, but there are other ways to
add items to a tuple.
1. Convert into a list: Just like the workaround for changing a tuple, you can convert it into a list, add your
item(s), and convert it back into a tuple.

In [ ]:
# Convert the tuple into a list, add "orange", and convert it back into a tuple:
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)
print(thistuple)

('apple', 'banana', 'cherry', 'orange')

2. Add tuple to a tuple. You are allowed to add tuples to tuples, so if you want to add one item, (or many),
create a new tuple with the item(s), and add it to the existing tuple:

In [ ]:
# Create a new tuple with the value "orange", and add that tuple:
thistuple = ("apple", "banana", "cherry")
y = ("orange",)
thistuple += y
print(thistuple)

('apple', 'banana', 'cherry', 'orange')

### **Remove Items**
Note: You cannot remove items in a tuple.
Tuples are unchangeable, so you cannot remove items from it, but you can use the same workaround as we
used for changing and adding tuple items:

In [ ]:
# Convert the tuple into a list, remove "apple", and convert it back into a tuple
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)
print(thistuple)

('banana', 'cherry')

Or you can delete the tuple completely:

In [1]:
# The del keyword can delete the tuple completely:
thistuple = ("apple", "banana", "cherry")
del thistuple
  print(thistuple) #this will raise an error because the tuple no longer exists

IndentationError: unexpected indent (<ipython-input-1-c6ecb89f3c70>, line 4)

In [ ]:
# The del keyword can delete the tuple completely:
thistuple = ("apple", "banana", "cherry")
del thistuple
print(thistuple) #this will raise an error because the tuple no longer exists

### **Unpacking a Tuple**
When we create a tuple, we normally assign values to it. This is called `packing` a tuple. But, in Python, we
are also allowed to extract the values back into variables. This is called `unpacking`.

In [2]:
fruits = ("apple", "banana", "cherry") # packing a tuple
(green, yellow, red) = fruits # unpacking a tuple
print(green)
print(yellow)
print(red)

apple
banana
cherry

**Note**: The number of variables must match the number of values in the tuple, if not, you must use an
asterisk to collect the remaining values as a list.

### **Using Asterisk**
If the number of variables is less than the number of values, you can add an `*` to the variable name and
the values will be assigned to the variable as a list:

In [3]:
# Assign the rest of the values as a list called "red":
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
(green, yellow, *red) = fruits
print(green)
print(yellow)
print(red)

apple
banana
['cherry', 'strawberry', 'raspberry']

If the asterisk is added to another variable name than the last, Python will assign values to the variable until
the number of values left matches the number of variables left.

In [4]:
# Add a list of values the "tropic" variable:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits
print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry

### **Tuple Methods**
Python has two built-in methods that you can use on tuples.
> `count()` : Returns the number of times a specified value occurs in a tuple

> `index()` : Searches the tuple for a specified value and returns the position of where it was found

In [5]:
mytuple = (1, 2, 3, 4, 3, 5, 3, 6)

countthree = mytuple.count(3)
print(f"Angka 3 muncul {countthree} kali dalam tuple.")

indexthree = mytuple.index(3)
print(f"Angka 3 pertama kali ditemukan pada indeks {indexthree}.")

Angka 3 muncul 3 kali dalam tuple.
Angka 3 pertama kali ditemukan pada indeks 2.

## **Set**
A set is a collection which is unordered, unchangeable **(but we can remove items and add new items)**, and
unindexed.
Sets are written with curly brackets.

In [6]:
# Create a Set:
thisset = {"apple", "banana", "cherry"}
print(thisset)

{'apple', 'cherry', 'banana'}

### **The `set()` Constructor**
It is also possible to use the `set()` constructor to make a set.

In [7]:
# Using the set() constructor to make a set:
thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
print(thisset)

{'apple', 'cherry', 'banana'}

### **Duplicates Not Allowed**
Sets cannot have two items with the same value.

In [9]:
# Duplicate values will be ignored:
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)

{'apple', 'cherry', 'banana'}

The values `True` and `1` are considered the same value in sets, and are treated as duplicates:

In [10]:
# True and 1 is considered the same value:
thisset = {"apple", "banana", "cherry", True, 1, 2}
print(thisset)

{True, 2, 'apple', 'cherry', 'banana'}

### **Access Items**
You cannot access items in a set by referring to an index or a key.
But you can loop through the set items using a `for` loop, or ask if a specified value is present in a set, by
using the `in` keyword.

In [11]:
# Loop through the set, and print the values:
thisset = {"apple", "banana", "cherry"}
for x in thisset:
 print(x)

apple
cherry
banana

### **Add Items**
Once a set is created, you cannot change its items, but you can add new items.
To add one item to a set use the `add()` method.

In [12]:
# Add an item to a set, using the add() method:
thisset = {"apple", "banana", "cherry"}
thisset.add("orange")
print(thisset)

{'orange', 'apple', 'cherry', 'banana'}

### **Add Sets**
To add items from another set into the current set, use the `update()` method.
The object in the `update()` method does not have to be a set, it can be any iterable object (tuples, lists,
dictionaries etc.).

In [13]:
# Add elements from list into thisset:
thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]
thisset.update(mylist)
print(thisset)

{'kiwi', 'cherry', 'orange', 'banana', 'apple'}

### **Remove Item**
To remove an item in a set, use the `remove() `, or the `discard()` method.
If the item to remove does not exist, `remove()` will raise an error, but `discard()` will **NOT** raise an
error.

In [15]:
thisset = {"apple", "banana", "cherry"}
thisset.remove("banana")
thisset.remove("apple")
thisset.discard("orange")
print(thisset)

{'cherry'}

You can also use the `pop()` method to remove an item, but this method will remove a random item, so
you cannot be sure what item that gets removed.
The return value of the `pop()` method is the removed item.

In [16]:
# Remove a random item by using the pop() method:
thisset = {"apple", "banana", "cherry"}
x = thisset.pop()
print(x)
print(thisset)

apple
{'cherry', 'banana'}

### **Join Two Sets (Union)**
There are several ways to join two or more sets in Python.
You can use the `update()` method that inserts all the items from one set into another as explained
above, or using the `union()` method that returns a new set containing all items from both sets.
Both `union()` and `update()` will exclude any duplicate items.

In [17]:
# The union() method returns a new set with all items from both sets:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}
set3 = set1.union(set2)
print(set3)

{'a', 1, 2, 3, 'c', 'b'}

### **Keep ONLY the Duplicates**
The `intersection_update()` method will keep only the items that are present in both sets.
The `intersection()` method will return a new set, that only contains the items that are present in both
sets

In [18]:
# Keep the items that exist in both set x, and set y:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.intersection_update(y)
print(x)
z = x.intersection(y)
print(z)

{'apple'}
{'apple'}

### **Keep All, But NOT the Duplicates**
The `symmetric_difference_update()` method will keep only the elements that are **NOT present** in
both sets.
The `symmetric_difference()` method will return a new set, that contains only the elements that are
**NOT present** in both sets

In [19]:
# Keep the items that are not present in both sets:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.symmetric_difference_update(y)
print(x)
z = x.symmetric_difference(y)
print(z)

{'cherry', 'google', 'banana', 'microsoft'}
{'apple', 'banana', 'cherry'}

## **Dictionary**
Dictionaries are used to store data values in key:value pairs.
A dictionary is a collection which is ordered, changeable and do not allow duplicates.
Dictionaries are written with curly brackets, and have keys and values

In [20]:
# Create and print a dictionary:
thisdict = {
 "brand": "Ford",
 "model": "Mustang",
 "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

### **Accessing Items**
You can access the items of a dictionary by referring to its key name, inside square brackets

In [21]:
# Print the "brand" value of the dictionary:
thisdict = {
 "brand": "Ford",
 "model": "Mustang",
 "year": 1964
}
print(thisdict["brand"])

Ford

There is also a method called `get()` that will give the same result

In [24]:
# Get the value of the "brand" key:
x = thisdict.get("brand")
print(x)

Ford

### **Get Keys**
The `keys()` method will return a list of all the keys in the dictionary

In [26]:
# Get a list of the keys:
x = thisdict.keys()
print(x)

dict_keys(['brand', 'model', 'year'])

The list of the keys is a view of the dictionary, meaning that any changes done to the dictionary will be
reflected in the keys list.

In [27]:
# Add a new item to the original dictionary, and see that the keys list gets upda
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.keys()
print(x) #before the change
car["color"] = "white"
print(x) #after the change

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])

### **Loop Through a Dictionary**
You can loop through a dictionary by using a `for` loop.
When looping through a dictionary, the return value are the keys of the dictionary, but there are methods to
return the values as well.

In [28]:
# Print all key names in the dictionary, one by one:
for x in thisdict:
 print(x)

# You can use the keys() method to return the keys of a dictionary:
for x in thisdict.keys():
 print(x)

# Print all values in the dictionary, one by one:
for x in thisdict:
 print(thisdict[x])

# You can also use the values() method to return values of a dictionary:
for x in thisdict.values():
 print(x)

brand
model
year
brand
model
year
Ford
Mustang
1964
Ford
Mustang
1964

Loop through both keys and values, by using the `items()` method:

In [29]:
for x, y in thisdict.items():
 print(x, y)

brand Ford
model Mustang
year 1964

### **Copy a Dictionary**
You cannot copy a dictionary simply by typing `dict2 = dict1` , because: `dict2` will only be a
reference to `dict1` , and changes made in `dict1` will automatically also be made in `dict2`. There are ways to make a copy one way is to use the built in Dictionary method `copy()`

In [30]:
# Make a copy of a dictionary with the copy() method:
thisdict = {
 "brand": "Ford",
 "model": "Mustang",
 "year": 1964
}
mydict = thisdict.copy()
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

### **Nested Dictionaries**
A dictionary can contain dictionaries, this is called nested dictionaries.

In [35]:
# Create a dictionary that contain three dictionaries:
myfamily = {
 "child1" : {
 "name" : "Emil",
 "year" : 2004
 },
 "child2" : {
 "name" : "Tobias",
 "year" : 2007
 },
 "child3" : {
 "name" : "Linus",
 "year" : 2011
 }
}
# Access nested dictionaries using the keys and dictionary name. Corrected typos in 'child2' and 'child3'
print(myfamily["child1"])
print(myfamily["child2"])
print(myfamily["child3"])

{'name': 'Emil', 'year': 2004}
{'name': 'Tobias', 'year': 2007}
{'name': 'Linus', 'year': 2011}

### **Access Items in Nested Dictionaries**
To access items from a nested dictionary, you use the name of the dictionaries, starting with the outer
dictionary:

In [36]:
# Print the name of child 2:
print(myfamily["child2"]["name"])

Tobias

# **Exerxise**

In [ ]:
for i in range(20):
  if i%2 == 0:
    print(i)

0
2
4
6
8
10
12
14
16
18

In [ ]:
a = [1,2,3]
b = a.copy()
c = a
c[0] = 100
print(a)
print(b)
print(c)

[100, 2, 3]
[1, 2, 3]
[100, 2, 3]

In [ ]:
n = 5
for i in range(n):
  for j in range(n-i):
    print("*", end=" ")
  print()

* * * * *
* * * *
* * *
* *
*

In [ ]:
a = [1,2,3,4]
a[0] = 10
print(a)

[10, 2, 3, 4]